name: kit_video_media
description: Native implementation for video playback in package:media_kit.
version: 1.0.0
topics:
  - video
  - video-player
  - audio
  - audio-player
  - cross-platform

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.1.11

  synchronized: ^3.1.0
  wakelock_plus: ^1.1.1
  screen_brightness: ^2.0.1
  volume_controller: ^2.0.7
  universal_platform: ^1.0.0+1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0



flutter:
  plugin:
    platforms:
      windows:
        pluginClass: KitVideoMediaPluginCApi
      linux:
        pluginClass: KitVideoMediaPlugin
      macos:
        pluginClass: KitVideoMediaPlugin
      ios:
        pluginClass: KitVideoMediaPlugin
      android:
        package: com.alexmercerind.kit_video_media
        pluginClass: KitVideoMediaPlugin
      web:
